### PR TITLE
[Refund] Fix partial refunds from admin panel not being sent to Mollie

### LINKED ISSUE #296: Partial refunds from Sylius admin not processing anymore in Mollie since change in 2.2.4 (#246)
#246  was fixed in 2.2.4: partial refunds created in Mollie dashboards aren't repeating anymore.

BUT!

Partial refunds created in **Sylius admin** aren't processed anymore in Mollie.
Logging shows: Skipping refund: already processed for this order and amount

Nothing is created / pushed to Mollie

The logic that was added for fixing #246 is causing this behaviour.

Can you please check

### PR DESCRIPTION
**Pull request by NoResponseMate**
Should fix #296 while still covering the previous #246

### CODE REVIEW

**Review by Cholin2000 — APPROVED** [review]

File: src/EventListener/PaymentPartialEventListener.php [hunk 1]
```diff
@@ -13,54 +13,109 @@
...
+            }
+
+            return (int) ((float) $molliePayment->amountRefunded->value * $this->divisorProvider->getDivisor());
+        } catch (\Exception $e) {
+            $this->loggerAction->addNegativeLog(
+                sprintf('Failed to get Mollie payment %s: %s', $paymentMollieId, $e->getMessage()),
+            );
 
-            $this->loggerAction->addNegativeLog($previousException->getMessage());
+            return 0;
```
Comment (TheMilek) [inline src/EventListener/PaymentPartialEventListener.php:104]: Shouldn't we here prevent from continueing refund?

Comment (NoResponseMate) [reply src/EventListener/PaymentPartialEventListener.php:104]: This whole action gets called after a refund on sylius' side has already been created, at which point, if we get a `0` from mollie, the check at line 67 will return early.

**Review by TheMilek — APPROVED** [review]
